### ISSUE TITLE
Will LucidFusion perform well with only one unposed image?

### ISSUE THREAD

**Issue by Colezwhy** [EnVision-Research/LucidFusion#1]
For example, the objects that are not in the canonical view. Like the image below, the woman is not in her front view.
I wonder how LucidFusion will perform under this setting.
![image](https://github.com/user-attachments/assets/93f49f02-9e51-4756-8ce7-1acc5832227f)

**Comment by heye0507** [comment]
Hi, thanks for your interest in our project! Currently, LucidFusion is trained on Obajverse data, which assumes an object-centric setting. This means it may face challenges when applied outside that context. However, we do have some promising examples from our lab where we reconstructed human bodies using iPhone captures. We've tested inputs with 3-7 images, and the results have been quite successful.

Here I attach a point cloud screenshot as I am a little concerned of privacy issues. Happy to chat more if needed.
![temp00](https://github.com/user-attachments/assets/2712b44c-a00e-47ed-86c1-61d044058dc5)
