### ISSUE TITLE
Export to obj or fbx mesh/texture

### ISSUE THREAD

**Issue by sekkit** [EnVision-Research/LucidFusion#3]
Is it possible?

**Comment by heye0507** [comment]
Hi, thanks for you intereseted. 

The short answer is we currently do not support directly output mesh/texture mesh, and our team also debating what would be the best way to get the mesh out of it.

However, there are a couple of ways you could try, given the point cloud we get from LucidFusion. If you haven't seen it, you can take a look at our project page with interactive viewer! As you can see, we can obtain a very dense Gaussian / point cloud from RCM representation. 
https://heye0507.github.io/LucidFusion_page/

Another simple approach would be to use LGM's mesh extraction method to obtain the mesh. 
https://github.com/3DTopia/LGM/tree/main

Best,

**Comment by sekkit** [comment]
ok, I'll try

**Comment by sekkit** [comment]
Traceback (most recent call last):
  File "/home/work/dev/LGM/convert.py", line 458, in <module>
    converter = Converter(opt).cuda()
  File "/home/work/dev/LGM/convert.py", line 79, in __init__
    self.gaussians = self.gs_renderer.load_ply(opt.test_path).to(self.device)
  File "/home/work/dev/LGM/core/gs.py", line 165, in load_ply
    opacities = np.asarray(plydata.elements[0]["opacity"])[..., np.newaxis]
  File "/home/sekkit/miniconda3/envs/DreamMat/lib/python3.10/site-packages/plyfile.py", line 717, in __getitem__
    return self.data[key]
  File "/home/sekkit/miniconda3/envs/DreamMat/lib/python3.10/site-packages/numpy/core/memmap.py", line 334, in __getitem__
    res = super().__getitem__(index)
ValueError: no field of name opacity
 when try LGM to convert the ply file, error appears.

**Comment by heye0507** [comment]
oh yup, we use a different point cloud format as LGM. If you want LGM format point cloud, you can save the predicted gaussian, and save it use LGM format. 

for example, you can do the following in the graph_ccm_stage_2_gs_square.py

'''
gs_vis = gaussians.clone().detach()
self.gs.save_ply(gs_vis, "file_name.ply")
'''

Then you can use "file_name.ply" with LGM.

**Comment by sekkit** [comment]
it worked! thx.
