### ISSUE TITLE
texture quality issue

### ISSUE THREAD

**Issue by sekkit** [EnVision-Research/LucidFusion#5]
when convert from ply to glb, there are holes in mesh and low quality uv texture produced. Even increase the resolution doesn't help. How to make the texture as good as in the video?

**Comment by heye0507** [comment]
Hi Sekkit, 

As I mentioned in the previous post #3, the conversion of GS to mesh is an ongoing research effort, and it is not our intention for LucidFusion to produce textured mesh.

LGM provides a way to convert the GS to mesh (through per-scene optimized NeRF), however, we think there might be other ways to do it (as your goal, good quality of texture mesh).

There is no answer to the question yet, and many other researchers are also working on it. If you are interested, you can check things like CRM, craftsman, NKSR, unqiue3D... etc.

Hope that helps!

**Comment by sekkit** [comment]
ok, get it. Will try it in the future
